apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: flask-app-tembici

resources:
- deployment.yaml
- hpa.yaml
- ingress.yaml
- managed-certificate.yaml
- service.yaml