apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: hlg
  name: tembici-sre-apps-hlg
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-app
    env: hlg
  name: flask-app
  namespace: tembici-sre-apps-hlg
spec:
  ports:
  - name: flask
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: flask-app
    env: hlg
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
    env: hlg
  name: flask-app
  namespace: tembici-sre-apps-hlg
spec:
  selector:
    matchLabels:
      app: flask-app
      env: hlg
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-app
        env: hlg
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Sao_Paulo
        image: us-central1-docker.pkg.dev/desafio-tembici-sre-1/sre-docker-registry/flask-app:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 25
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: flask-app
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/ping
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: flask-app
    env: hlg
  name: flask-app
  namespace: tembici-sre-apps-hlg
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app
  targetCPUUtilizationPercentage: 75
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  labels:
    app: flask-app
    env: hlg
  name: hlg-leosete7-com
  namespace: tembici-sre-apps-hlg
spec:
  domains:
  - flask-app-tembici-hlg.desafio-tembici-sre-1.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: gke-lb-ext-tembici-hlg
    networking.gke.io/managed-certificates: hlg-leosete7-com
  labels:
    app: flask-app
    env: hlg
  name: flask-app-hlg-ext
  namespace: tembici-sre-apps-hlg
spec:
  rules:
  - host: flask-app-tembici-hlg.desafio-tembici-sre-1.com
    http:
      paths:
      - backend:
          service:
            name: flask-app
            port:
              number: 8080
        path: /api/ping
        pathType: Prefix