apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: ClusterIP
  selector:
    greeting: flask-app
    version: one
  ports:
  - protocol: TCP
    port: 1001
    targetPort: 1000