apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app-hpa
spec:
  maxReplicas: 5
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: flask-app
      targetAverageUtilization: 60
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app