apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/ping
        pathType: Prefix
        backend:
          service:
            name: flask-app
            port:
              number: 8080
  - http:
      paths:
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: hello-world-2
            port:
              number: 8080