apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
      - flask-app-tembici-dev.leosete7.com
    secretName: my-tls-secret
  rules:
  - host: flask-app-tembici-dev.leosete7.com
    http:
      paths:
      - path: /v2
        pathType: ImplementationSpecific
        backend:
          service:
            name: hello-world-2
            port:
              number: 8000