# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount: 1

revisionHistoryLimit: 10

strategy:
  # activeDeadlineSeconds: 21600
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 0%
    # intervalSeconds: 1
    # timeoutSeconds: 600
    # updatePeriodSeconds: 1
  type: RollingUpdate

image:
  repository: us-central1-docker.pkg.dev/devops-sre-1/sre-docker-registry/flask-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler
securityContext: {}
terminationGracePeriodSeconds: 30

service:
  type: ClusterIP
  port: 8080

configmap:
  data: {}

hpa:
  minReplicas: {}
  maxReplicas: {}

ingress:
  enabled: true
  secretName: leosete7-tls
  annotations:
    kubernetes.io/ingress.class: nginx

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

resources: {}

nodeSelector:
  app: 'tembici-node-pool'        

tolerations: []

affinity: {}