apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app-tembici
  labels:
      name: flask-app-tembici
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app-tembici
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75