name: 1-CREATE-INFRA-GKE
on:
  workflow_dispatch:
    inputs:
      should-destroy:
        description: 'Run: terraform destroy -auto-approve?'
        default: false
        required: false
        type: boolean
      should-destroy-yes:
        description: 'Are you Sure? Run: terraform destroy -auto-approve?'
        default: false
        required: false
        type: boolean
  
jobs:
  gke_cluster:
    runs-on: ubuntu-latest
    env: ## Variables available in this workflow
      PROJECT_ID: "projc-devops-sete"
      REGION: "us-central1"
      CLUSTER_NAME: "leosete-cluster-prod"
      TF_ACTIONS_WORKING_DIR: "./terraform-gke/"
      PRIVATE_KEY: "private_key.pem"

    ## Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}

    steps:
      - name: 1-CHECKOUT ACTIONS
        uses: actions/checkout@v3


      - name: 2-AUTHENTICATE GOOGLE CLOUD
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_TERRAFORM_SVC_ACCOUNT }}

      - name: 3-SETUP CLOUD SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: 4-SETUP TERRAFORM
        uses: hashicorp/setup-terraform@v2
        with:
          # terraform_version: 1.2.7 ## Se não definida, usará default: latest
          terraform_version: ">=1.3" ## Se não definida, usará default: latest

      - name: 5-TERRAFORM FMT
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: 6-TERRAFORM INIT
        id: init
        run: terraform init

      - name: 7-TERRAFORM VALIDATE
        id: validate
        run: terraform validate 

      - name: 8-TERRAFORM PLAN
        if: ${{ inputs.should-destroy == false && inputs.should-destroy-yes == false }}
        id: plan
        run: terraform plan 
        continue-on-error: true

      - name: 9-TERRAFORM APPLY
        if: ${{ inputs.should-destroy == false && inputs.should-destroy-yes == false }}
        id: apply
        run: terraform apply -auto-approve

      - name: 10-TERRAFORM DESTROY
        if: ${{ inputs.should-destroy == true && inputs.should-destroy-yes == true }}
        id: destroy
        run: terraform destroy -auto-approve 
      
      - name: 11-GET KUBECONFIG CREDENTIALS
        if: ${{ inputs.should-destroy == false && inputs.should-destroy-yes == false }}
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.REGION }}

      - name: 12-CHECK GKE CLUSTER
        if: ${{ inputs.should-destroy == false && inputs.should-destroy-yes == false }}
        run: |
          gcloud container clusters list
          echo " "