name: 2-DEPLOY-FLASK-APP
on:
  push: 
    branches: [release*, feature*, hotfix*]
    tags: [v*]
  workflow_dispatch:

env: ## Variables available in this workflow
  PROJECT_ID: "fork-project-teste"
  CLUSTER_NAME: "tembici-cluster-prod"
  REGION: "us-central1"
  REPOSITORY: "sre-docker-registry"
  IMAGE_NAME: "flask-app"
  APPROVERS: "7700472077"
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: 1-CHECKOUT ACTIONS
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 2-AUTHENTICATE TO GOOGLE CLOUD
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_TERRAFORM_SVC_ACCOUNT }}

      - name: 3-SETUP CLOUD SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: 4-GET CREDENTIALS
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.REGION }}

      - name: 5-DOCKER METADATA
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value={{tag}}-{{sha}}

      - name: 6-BUILD DOCKER IMAGE
        run: |
          docker build -t ${{ steps.meta.outputs.tags }} .
          gcloud auth configure-docker  ${{ env.REGION }}-docker.pkg.dev --quiet

      # - name: 7-TESTING APPLICATION
      #   run: |
      #     docker run -t ${{ steps.meta.outputs.tags }} bash -c "BASE_API_ENV=test pipenv run pytest"

      # - name: 7-SEMANTIC VERSION
      #   id: semantic-version
      #   run: |
      #     bash ./scripts/semantic-version.sh
      
      # - name: 8-AUTOMATIC TAGGING OF RELEASES
      #   id: increment-git-tag
      #   run: |
      #     bash ./scripts/git_update.sh -v ${{ steps.semantic-version.outputs.semantic-version }}

      # - name: 8-PUSH DOCKER IMAGE TO ARTIFACT REGISTRY
      #   run: |
      #     docker tag ${{ steps.meta.outputs.tags }}  ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
      #     docker tag ${{ steps.meta.outputs.tags }}  ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$latest
      #     docker push  ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
      #     docker push  ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$latest

  # deploy_apps:
  #   needs: build_app
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       app_env: [dev, hlg, prd]
  #       include:
  #         - app_env: dev
  #           env_deploy: DEVELOPMENT
  #         - app_env: hlg
  #           env_deploy: HOMOLOG
  #         - app_env: prd
  #           env_deploy: PRODUCTION
  #     fail-fast: true ## se uma execução do job falhar, vai parar tudo
  #     max-parallel: 1
  #   env: ## Variables available in this job
  #     NS_APP: "tembici-sre-apps-${{ matrix.app_env }}"
  #     WORK_DIR: "./k8s"
  #   defaults:
  #     run:
  #       working-directory: ${{ env.WORK_DIR }}

  #   steps:
  #     - name: 1-CHECKOUT ACTIONS
  #       uses: actions/checkout@v3
  
  #     - name: 2-AUTHENTICATE TO GOOGLE CLOUD
  #       id: auth
  #       uses: google-github-actions/auth@v0
  #       with:
  #         credentials_json: ${{ secrets.GCP_TERRAFORM_SVC_ACCOUNT }}

  #     - name: 3-SETUP CLOUD SDK
  #       uses: google-github-actions/setup-gcloud@v0

  #     - name: 4-GET GKE CREDENTIALS
  #       uses: 'google-github-actions/get-gke-credentials@v0'
  #       with:
  #         cluster_name: ${{ env.CLUSTER_NAME }}
  #         location: ${{ env.REGION }}

  #     - name: 5-CHECK NAMESPACE TO DEPLOY
  #       continue-on-error: true
  #       run: |
  #         kubectl get ns ${{ env.NS_APP }}
  #         echo "The current Namespace is ${{ env.NS_APP }}"

  #     - name: 6-APPROVE OR DENY DEPLOY
  #       uses: trstringer/manual-approval@v1
  #       with:
  #         secret: ${{ github.token }}
  #         approvers: ${{ env.APPROVERS }}
  #         issue-title: "Deploying flask-app in ${{ matrix.env_deploy }}"

  #     - name: 7-APPLICATION APPROVED TO DEPLOY IN ${{ matrix.env_deploy }}
  #       run: |
  #         sleep 30
  #         kubectl apply -f deploy-${{ matrix.app_env }}.yaml

  # merge_master:
  #   needs: deploy_apps
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: 1-CHECKOUT ACTIONS
  #       uses: actions/checkout@v3

  #     - name: 2-APPROVE OR DENY MERGE TO MASTER
  #       uses: trstringer/manual-approval@v1
  #       with:
  #         secret: ${{ github.token }}
  #         approvers: ${{ env.APPROVERS }}
  #         issue-title: "Approve merge ${{ github.ref_name }} branch into master branch"

  #     - name: MERGE ${{ github.ref_name }} BRANCH INTO master BRANCH
  #       uses: devmasx/merge-branch@master
  #       with:
  #         type: now
  #         from_branch: ${{ github.ref_name }}
  #         target_branch: master
  #         github_token: ${{ github.token }}