name: 3-Flask App Deploy
on:
  push:
    branches: [release, feature, hotfix, task]
  workflow_dispatch:
    inputs:
      deploy-app-env:
        description: 'Select a k8s namespace to deploy'
        required: true
        default: 'tembici-sre-apps-dev'
        type: choice
        options:
        - tembici-sre-apps-dev 
        - tembici-sre-apps-hlg
        - tembici-sre-apps-prod ## Add namespaces here if needed.

env: ## Variables available in this workflow
  NS_ENV: ${{ inputs.deploy-app-env }}
  PROJECT_ID: "tembici-sre"
  CLUSTER_NAME: "tembici-sre-cluster-prod"
  REGION: "us-central1"
  REPOSITORY: "sre-docker-registry"
  IMAGE_NAME: flask-app

jobs:
  manage_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Get Credentials
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.REGION }}

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts-github/git_update.sh -v major

      - name: Teste Flask APP
        run: |
          docker run -t ${{ env.IMAGE_NAME }}:latest bash -c "BASE_API_ENV=test pipenv run pytest"

      - name: Configure Docker Client
        run: |
          gcloud auth configure-docker  ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest  ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          docker tag ${{ env.IMAGE_NAME }}:latest  ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$GIT_TAG
          docker push  ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          docker push  ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$GIT_TAG

      - name: Namespace to Deploy
        run: |
          kubectl get ns ${{ inputs.deploy-app-env }}
          echo "Namespace to deploy is ${{ inputs.deploy-app-env }}"

      - name: Apply/Create K8s Resources
        run: |
          cd k8s
          kubectl apply -f '*.yaml' -n ${{ inputs.deploy-app-env }}

      ## BUILD >> BUSCAR/PULL DA IMAGEM BASE + COD DO APP
      ## TEST DO APP
      ## PUBLISH DO APP >> ENVIAR PARA ARTIFACT REGISTRY - GCP
      ## GERAR VERSIONAMENTO - GIT VERSION???
      ## CONTROLAR RELEASES - DE QUAL FORMA (XLRELEASE)???
      ## MONITORAÇÃO
      ## LOGS
      ## SEGURANÇA DA CONTA GCP - IAM/SERVICE ACCOUNTS?
      ## SEGURANÇA DO CLUSTER GKE - RBAC???


      # # Set up kustomize
      # - name: Set up Kustomize
      #   run: |-
      #     curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
      #     chmod u+x ./kustomize
  
      # # Deploy the Docker image to the GKE cluster
      # - name: Deploy
      #   run: |-
      #     ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
      #     ./kustomize build . | kubectl apply -f -
      #     kubectl rollout status deployment/$DEPLOYMENT_NAME
      #     kubectl get services -o wide
