name: Create Infra - GKE
on:
  push:
    branches: [infra]

  workflow_dispatch:
    inputs:
      should-destroy:
        description: 'Run: terraform destroy -auto-approve? (desmarcado = false)'
        default: false
        required: false
        type: boolean
  
jobs:
  create_gke_cluster:
    runs-on: ubuntu-latest
    env:
      # tf_actions_working_dir: "./infra-gcp/terraform/"
      tf_actions_working_dir: "./terraform-gke/"
    ## Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
  
      ## TO RUN WITH GKE MODULE
      - name: Enable Compute and Container APIs
        if: ${{ inputs.should-destroy == false }}
        run: |
          gcloud services enable compute.googleapis.com container.googleapis.com artifactregistry.googleapis.com
          gcloud services list --enabled |egrep "compute.googleapis.com|container.googleapis.com|artifactregistry.googleapis.com"
  
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.7 ## Se não definida, usará default: latest

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate 

      - name: Terraform Plan
        id: plan
        run: terraform plan 
        continue-on-error: true

      - name: Terraform Apply
        if: ${{ inputs.should-destroy == false }}
        id: apply
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ inputs.should-destroy == true }}
        id: destroy
        run: terraform destroy -auto-approve 
      
      - name: Get GKE Cluster Kubeconfig
        if: ${{ inputs.should-destroy == false }}
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          gcloud container clusters get-credentials tembici-devops-sre-prod --region us-central1 --project xenon-axe-359616

      - name: Check GKE Cluster
        if: ${{ inputs.should-destroy == false }}
        run: |
          gcloud container clusters list
          echo " "
          echo " "
          kubectl get nodes
