name: Deploy Flask App
on:
  push:
    branches:
      - 'release-**'
      - 'hotfix-**'
      - 'feature-**'
  pull_request:
  workflow_dispatch:
    inputs:
      should-deploy:
        description: 'Should deploy app? (desmarcado = false)'
        default: false
        required: false
        type: boolean
  
jobs:
  create_gke_cluster:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "tembici-flask-app"

    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Get GKE Cluster Kubeconfig
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          gcloud container clusters get-credentials tembici-devops-sre-prod --region us-central1 --project xenon-axe-359616

      - name: Create/Verify Namespace
        if: ${{ inputs.should-deploy == true }}
        run: |
          kubectl get ns
          kubectl create ns ${APP_NAME}
