name: Deploy Flask App
on:
  push:
    branches:
      - 'release-**'
      - 'hotfix-**'
      - 'feature-**'
  pull_request:
  workflow_dispatch:
    inputs:
      should-deploy:
        description: 'Should deploy app? (desmarcado = false)'
        default: false
        required: false
        type: boolean
  
jobs:
  create_gke_cluster:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: "tembici-devops-apps"

    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Get GKE Cluster Kubeconfig
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          gcloud container clusters get-credentials tembici-devops-sre-prod --region us-central1 --project xenon-axe-359616

      - name: Verify if Namespace Exist
        run: |
          echo "CHECK_NS=`kubectl get ns $NAMESPACE |grep $NAMESPACE |awk '{print $1}'`" >> $GITHUB_ENV

      - name: Create Namespace
        if: ${{ env.CHECK_NS != env.NAMESPACE }}
        continue-on-error: true
        run: |
          kubectl create ns $NAMESPACE

      - name: List All Namespaces
        run: |
          kubectl get ns

      - name: Apply K8s files
        # if: ${{ inputs.should-deploy == true }}
        run: |
          kubectl apply -f .k8s/ingress.yaml -n $NAMESPACE