name: DEPLOY PROMETHEUS AND GRAFANA

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: "projc-devops-sete"
  CLUSTER_NAME: "leosete-cluster-prod"
  REGION: "us-central1"

jobs:
  monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: 1-CHECKOUT ACTIONS
        uses: actions/checkout@v2

      - name: 2-AUTHENTICATE TO GOOGLE CLOUD
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_TERRAFORM_SVC_ACCOUNT }}

      - name: 3-SETUP CLOUD SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: 4-GET CREDENTIALS
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.REGION }}

      - name: INSTALL HELM
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        shell: bash

      - name: ADD HELM REPOSITORY
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
        shell: bash

      - name: INSTALL KUBE-PROMETHEUS
        if: ${{ github.event.head_commit.author.name == 'Bot' }}
        run: |
          helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --set grafana.enabled=true --namespace monitoring
        shell: bash

      - name: UPGRADE NGINX "HELLO WORLD"
        run: |
          helm upgrade hello-world bitnami/nginx --namespace hello-world-app
        shell: bash

      - name: VERIFY KUBE-PROMETHEUS AND GRAFANA AVAILABILITY
        run: |
          kubectl get pods --namespace monitoring | grep prometheus-operator
          kubectl get pods --namespace monitoring | grep grafana
        shell: bash

      - name: ROLLBACK KUBE-PROMETHEUS AND GRAFANA IF THEY ARE NOT AVAILABLE
        if: steps.verify-kube-prometheus-and-grafana-availability.outcome == 'failure'
        run: |
          helm rollback kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring
        shell: bash


    
      # - name: 5-KUBE PROMETHEUS - FORK LEO SETE ## https://github.com/prometheus-operator/kube-prometheus
      #   run: |
      #     git clone https://github.com/leonardosete/kube-prometheus
      #     cd kube-prometheus
      #     kubectl create -f manifests/setup
      #     kubectl apply -f manifests
