name: DEPLOY PROMETHEUS AND GRAFANA

on:
  workflow_dispatch:

env: ## Variables available in this workflow
  PROJECT_ID: "devops-project-leosete"
  CLUSTER_NAME: "leosete-cluster-prod"
  REGION: "us-central1"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1-CHECKOUT ACTIONS
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 2-AUTHENTICATE TO GOOGLE CLOUD
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_TERRAFORM_SVC_ACCOUNT }}

      - name: 3-SETUP CLOUD SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: 4-GET CREDENTIALS
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.REGION }}

      - name: INSTALL HELM
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: DEPLOY PROMETHEUS
        run: |
          helm install prometheus prometheus-community/prometheus --namespace=prometheus --values=./k8s-monitoring/values-prom.yaml


      # - name: DEPLOY GRAFANA
      #   run: |
      #     helm install grafana prometheus-community/grafana --namespace=grafana


      # - name: 5-CREATE K8s OBJECTS
      #   run: |
      #     kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
      #     kubectl apply -f ./k8s-monitoring/grafana.yaml
      #     kubectl apply -f ./k8s-monitoring/prometheus.yaml
      #     kubectl apply -f ./k8s-monitoring/servicemonitor.yaml