name: DEPLOY PROMETHEUS AND GRAFANA

on:
  workflow_dispatch:

env: ## Variables available in this workflow
  PROJECT_ID: "devops-project-leosete"
  CLUSTER_NAME: "leosete-cluster-prod"
  REGION: "us-central1"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1-CHECKOUT ACTIONS
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 2-AUTHENTICATE TO GOOGLE CLOUD
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_TERRAFORM_SVC_ACCOUNT }}

      - name: 3-SETUP CLOUD SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: 4-GET CREDENTIALS
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.REGION }}

      - name: 4-KUBE PROMETHEUS
        run: |
          git clone https://github.com/leonardosete/kube-prometheus
          cd kube-prometheus
          kubectl create -f manifests/setup
          kubectl get customresourcedefinitions.apiextensions.k8s.io -n monitoring
          kubectl create -f manifests
          kubectl get pods -n monitoring